# -*- coding: utf-8 -*-
"""tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IYVXbNcQs2sRXa1Kh9FHvylJgEnssw3
"""

!pip install gTTS pydub deep-translator ffmpeg-python

from gtts import gTTS
from deep_translator import GoogleTranslator
from IPython.display import Audio, display
from pydub import AudioSegment
import os

# Set up ffmpeg path (for Colab)
os.environ["PATH"] += os.pathsep + "/usr/bin"

text_en = "Let's play cricket today."

languages = {
    "English": ("en", text_en),
    "Spanish": ("es", None),
    "Arabic": ("ar", None),
    "Tamil": ("ta", None),
    "Telugu": ("te", None)
}

# Translate
for lang in ["Spanish", "Arabic", "Tamil", "Telugu"]:
    translated = GoogleTranslator(source='en', target=languages[lang][0]).translate(text_en)
    languages[lang] = (languages[lang][0], translated)

# Generate audio with 800ms silence at start
for lang_name, (lang_code, translated_text) in languages.items():
    print(f"\n🔊 {lang_name} Audio")
    print(f"📝 Text: {translated_text}")

    # Generate speech
    tts = gTTS(text=translated_text, lang=lang_code)
    raw_file = f"{lang_code}_raw.mp3"
    final_file = f"{lang_code}_final.mp3"
    tts.save(raw_file)

    # Add silence at start
    speech = AudioSegment.from_file(raw_file, format="mp3")
    silence = AudioSegment.silent(duration=800)  # 800ms leading silence
    padded = silence + speech
    padded.export(final_file, format="mp3")

    # Play audio
    display(Audio(final_file))

